project:
  type: website
  output-dir: build

website:
  title: "DREAM Lab Coder Workspaces"
  navbar:
    left:
      - text: Guides
        menu:
        - text: Connecting to Google Drive
          href: guides/gdrive.qmd
        - text: Getting Started with RStudio
          href: guides/rstudio.qmd
        - text: Using Marimo Notebooks
          href: guides/marimo.qmd
        - text: AI Gateway
          href: guides/ai-gateway.qmd
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto